name: Release-Nuget
on:
  workflow_run: 
    workflows: [ Tests ]
    types: [ completed ]
    branches: [ master ]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - name: debug
      run: echo ${{ toJSON(github.event) }}

  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.ref, 'refs/tags/v')
    env: 
      REF: ${{ github.event.workflow_run.ref }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Extract release notes
      run: |
        git log --pretty=format:'%d %s' $REF | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES

    - name: Set VERSION variable from tag
      run: echo "VERSION=${REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Validate version
      run: grep -i "<Version>${VERSION}" include/c#/10/HsBuildCodes.csproj

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build include/c#/10 --configuration Release

    - name: Pack
      run: dotnet pack include/c#/10 --configuration Release --no-build --output .
      
    # - name: Push
    #   run: dotnet nuget push NuGet.Workflow.${VERSION}.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${NUGET_API_KEY}
    #   env:
    #     NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}